### ISSUE TITLE
README.md points to spectre instead of bootstrap

### ISSUE THREAD

**Issue by synq** [ayozehd/grav-theme-bootstrap-blog#1]
In the first line of README.md
'Bootstrap Blog is a theme for Grav CMS built in Bootstrap v4.1 framework and provides a powerful base to develope your own theme using SCSS. Also we use latest FontAwesome 5.'

Bootstrap v4.1 links to https://picturepan2.github.io/spectre/ 
perhaps that should be this instead: https://getbootstrap.com/docs/4.1/

**Comment by ayozehd** [comment]
Ops you catched me! thanks for submitting
