### ISSUE TITLE
languages.yaml didn't work

### ISSUE THREAD

**Issue by trangthaonguyen** [ayozehd/grav-theme-bootstrap-blog#10]
Hi, 

Please take a look at Bootstrap-blog theme. Language in admin section didn't load. Please see the attached image
![Theme  Bootstrap Blog   Grav](https://user-images.githubusercontent.com/33317500/79965898-d2933b00-84b6-11ea-9054-c10ed07a37c2.png)
a

**Comment by ayozehd** [comment]
What Grav version are you using? Right now looks fine to me at `1.6.23`

**Comment by ayozehd** [comment]
That should be fixed in latest version [1.4.0](https://github.com/ayozehd/grav-theme-bootstrap-blog/releases/tag/1.4.0).

If doesn't work yet feel free to reopen the issue, thanks
