### ISSUE TITLE
Source of the blog?

### ISSUE THREAD

**Issue by rogorido** [ayozehd/grav-theme-bootstrap-blog#13]
Hi, many thanks for the beautiful and complete theme. Would it be possible to see the source of your blog (not the theme, the blog) to see how it is structured? many thanks in advance!

**Comment by ayozehd** [comment]
Thanks for your feedback @rogorido 

Many people have been asking for the same, and I think the best for everyone is build a [Skeleton](https://getgrav.org/downloads/skeletons) based on this theme. There you'll can see the pages structure, supported plugins and a full-site working on this theme taking advantage of all available options.

Can't give you an estimated time right now but will be available on this repo: [ayozehd/grav-skeleton-bootstrap-blog](https://github.com/ayozehd/grav-skeleton-bootstrap-blog)

**Comment by rogorido** [comment]
thanks for your answer. What would be the skeleton most similar to your theme?

**Comment by ayozehd** [comment]
Mmm every theme has different options, structures, and pages... but this theme is based on [getgrav/grav-theme-antimatter](https://github.com/getgrav/grav-theme-antimatter)

**Comment by ayozehd** [comment]
Just did a skeleton for this theme:

* https://github.com/ayozehd/grav-skeleton-bootstrap-blog
* https://github.com/ayozehd/grav-skeleton-bootstrap-blog-child-theme

**Comment by rogorido** [comment]
thanks and sorry for the delay!
