### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by koreos** [ayozehd/grav-theme-bootstrap-blog#4]
This is first theme for Grav for ordinary people who are not webmasters, developers, programmers or designers!!! 
Many people have been waiting for it! 
Make something like this https://generatepress.com/ or this https://oceanwp.org/ with your theme for Grav in the future and You will have a lot of money, I swear!

Grav is good CMS but only for developers, ordinary people have no time for change files on the server...

**Comment by ayozehd** [comment]
Thanks a lot for your comment! I dedicated a special effort easing usage for newcoming users.

Many features will get out very soon

**Comment by koreos** [comment]
Very good! 
Think about all important solutions for present internet (and Google) like: very easy to use, lightweight, speed, SEO, security and stable, accessibility WCAG, W3C validation, schema.org, and Your theme will be perfect!
For example https://generatepress.com/premium/ and https://oceanwp.org/extensions/ and https://wordpress.org/plugins/autodescription/ will be nice to see in Your theme, but I know that it is a lot of work..

**Comment by ayozehd** [comment]
Right now I prefer delegate meta tags behaviour to a Grav plugin like this https://github.com/paulmassen/grav-plugin-seo 
Anyway all them are very good **pull requests**. Some of next steps will be manifest.json, w3c validation and refactorize macros.
