### ISSUE TITLE
Macro button gives incorrect url

### ISSUE THREAD

**Issue by FrancoUd** [ayozehd/grav-theme-bootstrap-blog#6]
A website that i'm testing resides in a "grav02" subfolder. In a blog page, the "page.url" of an item is (correctly): 
/grav02/fr/albums/item1

but when the "read more" button is rendered, the url becomes:

/grav02/grav02/fr/albums/nuovo-1

I think the problem is in  the  templates/macros/bootstrap_tools.html.twig, at line 45:
`  <a href="{{ url starts with 'http' ? url : url(url) }}" alt="{{ text }}"`

Problem is: my url doesn't start with http (it starts with "/grav02") ; then the url function give an incorrect value (/grav02/grav02/etc). 

Any idea about how to fix it? Shouldn't rather be:
`  <a href="{{ url starts with 'http' ? url(url) : url }}" alt="{{ text }}"`

? thanks!

**Comment by ayozehd** [comment]
That's an old function and is not needed anymore. I will remove it in next tag.

Thank you for report it!
