### ISSUE TITLE
compiled css

### ISSUE THREAD

**Issue by vklepper** [ayozehd/grav-theme-bootstrap-blog#7]
Hi Ayozehd,

I just start to use you theme and have a little issue. I am a beginner in frontend and compiled css. When I try to compile css, I got 

> Can't find stylesheet to import.

>  @import "bootstrap/functions";

I use your shell script located in user/themes/bootstrap-blog/scss.sh

Do you have any ideas ? 

By the way, thanks you ! :)

**Comment by vklepper** [comment]
I found a fix. I don't know if it's cleans but it's work ^^

> user/themes/bootstrap-blog/assets/scss/template/configuration/_functions.scss
```
@import "../../bootstrap/functions";
@import "../../bootstrap/variables";
@import "../../bootstrap/mixins";
```

**Comment by ayozehd** [comment]
Thanks for report @vklepper yesterday I found same bug in local development. Btw the bug indeed is related to filename of `user/themes/bootstrap-blog/assets/scss/template/configuration/all.scss`, which should start as "_" (underscore). I will upload a fix soon.

**Comment by ayozehd** [comment]
Latest update [1.3.2](https://github.com/ayozehd/grav-theme-bootstrap-blog/releases/tag/1.3.2) should fix this issue
