### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by bluis4** [ayozehd/grav-theme-bootstrap-blog#9]
Are there any skeleton for this theme ? Somehow, cannot find it on the grav skeleton download section

Regards,

Luke

**Comment by ayozehd** [comment]
No there's not any Skeleton for this theme yet. 

Won't be too much hard to create since I have blog/docs built-in a Github repo. But need to find some time to manage it, thanks for remember me this to-do ;)

**Comment by ayozehd** [comment]
Done!
* https://github.com/ayozehd/grav-skeleton-bootstrap-blog
* https://github.com/ayozehd/grav-skeleton-bootstrap-blog-child-theme
